teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1  # Left Stick Vertical
      y: 0  # Left Stick Horizontal
    scale_linear:
      x: 0.5  # Max 0.5 m/s
      y: 0.5
    scale_linear_turbo:
      x: 1.0  # Max 1.0 m/s with turbo
      y: 1.0
    
    axis_angular:
      yaw: 3  # Right Stick Horizontal
    scale_angular:
      yaw: 1.0  # Max 1.0 rad/s
    scale_angular_turbo:
      yaw: 2.0

    enable_button: 5  # RB (Right Bumper) as deadman switch
    enable_turbo_button: 7 # RT (Right Trigger) or adjust as needed
    require_enable_button: true
